Traceback (most recent call last):
  File "C:\Knights_tour\drl_gnn_py39\lib\site-packages\gym\envs\registration.py", line 158, in spec
    return self.env_specs[id]
KeyError: 'KnightTour-v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Knights_tour\DQN\train_DQN.py", line 261, in <module>
    env_training = gym.make(ENV_NAME)  # Training environment
  File "C:\Knights_tour\drl_gnn_py39\lib\site-packages\gym\envs\registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "C:\Knights_tour\drl_gnn_py39\lib\site-packages\gym\envs\registration.py", line 128, in make
    spec = self.spec(path)
  File "C:\Knights_tour\drl_gnn_py39\lib\site-packages\gym\envs\registration.py", line 203, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: KnightTour-v1
